### ISSUE TITLE
[高]ヘッダーからのフリーワード検索をできるようにする

### ISSUE THREAD

**Issue by chihiro0415** [ArisaNAKAMURA-GitHub/sweetsguide#38]
layout.blade.php：16行目あたり、
` <form method="get" action="#" class="search_container">` ここでactionが指定されていないので修正する

**Comment by ArisaNAKAMURA-GitHub** [comment]
ルートはweb.phpの下の方に書いてあるのでactionへの追加をお願いします。

**Comment by chihiro0415** [comment]
inputタグにname属性も入っていないようす

**Comment by ArisaNAKAMURA-GitHub** [comment]
一応対応済でPRあげてます
