### ISSUE TITLE
[高] indexページ（top）が表示されない（viewファイルを正しい場所に作成する）

### ISSUE THREAD

**Issue by chihiro0415** [ArisaNAKAMURA-GitHub/sweetsguide#39]
ページのルートが諸々ずれちゃっているせいもあると思うので
Reviews/show.blade.php のviewページを stores/show.blade.php に移行してあげる

**Comment by mamiko-7172** [comment]
@chihiro0415  @ArisaNAKAMURA-GitHub 
これはどこにどう作ったらいいのでしょうか？

**Comment by ArisaNAKAMURA-GitHub** [comment]
ページの把握を間違えました。今Reviewsフォルダに入ってるshowページは野呂さんが作ったページですね。
割り振りしなおします。

**Comment by ArisaNAKAMURA-GitHub** [comment]
@mamiko-7172 
ページの把握を間違えました。今Reviewsフォルダに入ってるshowページは野呂さんが作ったページですね。
割り振りしなおします
