### ISSUE TITLE
[PR中][高]ヘッダーのロゴからtopページへ遷移できる

### ISSUE THREAD

**Issue by chihiro0415** [ArisaNAKAMURA-GitHub/sweetsguide#41]
topページへ戻る経路がないので
ログイン→マイページ、からの行き先がなくて詰んでしまう:eyes:

**Comment by tai-namechan** [comment]
#43 のデザイン整えるついでにaタグつけたんですけど、okuyaさんいそがしかったら検索フォームのprと一緒にあげます！
