### ISSUE TITLE
[PR中][低] ヘッダーのフリーワード検索フォームのスタイル修正

### ISSUE THREAD

**Issue by chihiro0415** [ArisaNAKAMURA-GitHub/sweetsguide#43]
### 現状
<img width="300" alt="スクリーンショット 2021-06-15 12 30 34" src="https://user-images.githubusercontent.com/30280895/121988573-8ea77780-cdd5-11eb-8e63-3d10401b84b2.png">

### 理想
<img width="300" alt="スクリーンショット 2021-06-15 12 30 55" src="https://user-images.githubusercontent.com/30280895/121988588-949d5880-cdd5-11eb-884e-86d50b0a6ab6.png">

**Comment by tai-namechan** [comment]
できました！prあげてもいいですか！
![スクリーンショット 2021-06-16 16 28 25](https://user-images.githubusercontent.com/76046768/122176742-e7533f00-cebf-11eb-93fe-fe82ed6377dd.png)

**Comment by Tomo9996** [comment]
行川さんはや！！　さすがすごいですね
