### ISSUE TITLE
[PR中]ログアウトができない

### ISSUE THREAD

**Issue by tai-namechan** [ArisaNAKAMURA-GitHub/sweetsguide#45]
登録後、ヘッダーの自分の名前のとこをクリックしてもログアウトのボタンが出てこない

**Comment by tai-namechan** [comment]
奥谷さんのprのブランチでのことでした。。。
ミスりました

**Comment by ArisaNAKAMURA-GitHub** [comment]
クラス名とかが変わっちゃったのか、：：afterが効いていなさそうな感じです。

**Comment by tai-namechan** [comment]
linkのとこにjsの

        <script src="{{ asset('js/app.js') }}" defer></script>
を加えたらログアウトできるようになりました
headのtitleの下あたりに入れればいいと思います
