### ISSUE TITLE
［高］口コミ詳細ページ（お店の詳細ページ）でcssが効いていない

### ISSUE THREAD

**Issue by ArisaNAKAMURA-GitHub** [ArisaNAKAMURA-GitHub/sweetsguide#48]
reviewフォルダの中のshowページ
reset.cssの波かっこの外に`”`がなくて下のstyle.cssのlinkタグまで””文字としてとらえられていると思います。
```
<link rel="stylesheet" href="{{ asset('css/reset.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}">
```
ダブルクォーテーションの位置を調整する必要があります。

**Comment by ghost** [comment]
https://github.com/ArisaNAKAMURA-GitHub/sweetsguide/pull/52 で修正してPR上げました。
