### ISSUE TITLE
［高］口コミ詳細ページ（＝店の詳細ページ）のデータがとってこれていない

### ISSUE THREAD

**Issue by ArisaNAKAMURA-GitHub** [ArisaNAKAMURA-GitHub/sweetsguide#49]
$store->addressなどのところの$storeって何？ってエラーが出てきました。

**Comment by Ako-in** [comment]
#55でコメントしたものと同じでしょうか。。。

口コミが表示されていないので、
{{$review->comment}}を追加する必要があると思います。
投稿者の名前は{{$review->user_id}}ではないでしょうか？
