### ISSUE TITLE
［高］createページに飛べない&createページの店舗情報が渡ってない

### ISSUE THREAD

**Issue by tai-namechan** [ArisaNAKAMURA-GitHub/sweetsguide#51]
207行め、下書き保存のpublished_atが取得できてないみたいです

**Comment by tai-namechan** [comment]
口コミ対象の店舗情報が渡ってきてないです

**Comment by ArisaNAKAMURA-GitHub** [comment]
恐らく既出のPRで中川さんが修正中

**Comment by ArisaNAKAMURA-GitHub** [comment]
207行目のpulished_atのところは野呂さんにお願いします。
`syntax error, unexpected ':', expecting '(' (View: C:\xampp\htdocs\sweetsguide\resources\views\Reviews\create.blade.php)`
ってエラーが返ってきますが、：って書かれてないんですよね…

**Comment by ArisaNAKAMURA-GitHub** [comment]
https://engineer-class.slack.com/archives/G01GL8E1PGF/p1623759405274900

**Comment by chihiro0415** [comment]
こちらで対応してもらいます！
https://github.com/ArisaNAKAMURA-GitHub/sweetsguide/issues/68
