### ISSUE TITLE
［高］Show.Blade.phpが表示されない？

### ISSUE THREAD

**Issue by Ako-in** [ArisaNAKAMURA-GitHub/sweetsguide#55]
前回の授業の最後の方でも少し触れてますが、
ファイル名がReviewsではなく、Storesフォルダを作成して、Show.Blade.phpを移動させる必要があるようです。

154行目のForeach文ですが
@foreach ($store->reviews as $review)ではないでしょうか？

もし既に出ている内容でしたらすみません。。。

**Comment by chihiro0415** [comment]
これ同じですかね！

https://github.com/ArisaNAKAMURA-GitHub/sweetsguide/issues/39

**Comment by chihiro0415** [comment]
@Ako-in 
>154行目のForeach文ですが
>@foreach ($store->reviews as $review)ではないでしょうか？

これは何のファイルの話でしょうか？？:eyes:

**Comment by Ako-in** [comment]
@chihiro0415 
同じくshow.blade.phpです。
真ん中の$reviews の$がいらないのでは？と思いました。

**Comment by ArisaNAKAMURA-GitHub** [comment]
@Ako-in  試しに変えてみて表示されたのでそうだと思います。

**Comment by ArisaNAKAMURA-GitHub** [comment]
分けられていると見づらいので＃39を消しました。

井上さんより↓↓↓
> 口コミが表示されていないので、
{{$review->comment}}を追加する必要があると思います。


> 投稿者の名前は{{$review->user_id}}ではないでしょうか？

**Comment by Ako-in** [comment]
@ArisaNAKAMURA-GitHub 
他のIssuesを細かく確認できておらず。。フォローありがとうございます！

**Comment by ArisaNAKAMURA-GitHub** [comment]
店舗情報とその店がもつ口コミが入ってくるところだと思います。
indexページから続きを見る・・・をクリックしたときにstores.showを通っていて、storesテーブルを参照してから$storeを返しているので店舗情報のところと口コミのところで取り出し方は変わると思います。
手元で試しにやってみて、
店舗のところでは現状では`trying to get property of non-object `と物がないよーとエラーが出てきました。
` <dd>{{$store->address??""}}</dd>`
に変更して表示はされましたが他にもいい方法はありそうです。
口コミのところで現状では`$reviews is undefined`とエラーが出てきました。
井上さんのおっしゃる通り` @foreach ($store->reviews as $review)`に変更する必要がありそうで、
かつ` {{$review->user->name}}さんの口コミ`で名前が出てきました。

**Comment by chihiro0415** [comment]
このPRが通ったら改善される予定
https://github.com/ArisaNAKAMURA-GitHub/sweetsguide/pull/52
