### ISSUE TITLE
edit.blade.phpから上書き保存を押すと投稿が消えちゃう

### ISSUE THREAD

**Issue by tai-namechan** [ArisaNAKAMURA-GitHub/sweetsguide#59]
上書き保存したら上書きした投稿がマイページから消えてました

**Comment by tai-namechan** [comment]
edit.blade.phpのformタグに位置を変えれば解決すると思います

**Comment by chihiro0415** [comment]
このissueはこのPRで解決しそうですね
https://github.com/ArisaNAKAMURA-GitHub/sweetsguide/pull/36/files#
