### ISSUE TITLE
［PR中］create.blade.phpに店舗情報が表示されない

### ISSUE THREAD

**Issue by ArisaNAKAMURA-GitHub** [ArisaNAKAMURA-GitHub/sweetsguide#77]

**Comment by ArisaNAKAMURA-GitHub** [comment]
foreach~endforeachが書かれていない
表示させる部分に呼びだすための{{ }}がない

**Comment by ArisaNAKAMURA-GitHub** [comment]
表示させる部分に呼びだすための{{ $store->○○ }}がない
画像の黄色い〇のところのように書いていく必要がある
![無題oo](https://user-images.githubusercontent.com/73116350/122302271-d563b180-cf3c-11eb-8e89-4c7f641cf591.png)

**Comment by ArisaNAKAMURA-GitHub** [comment]
平均値のところは中川さんが対応中
平均値終わり次第こっちに合流

**Comment by mamiko-7172** [comment]
https://github.com/ArisaNAKAMURA-GitHub/sweetsguide/pull/92

**Comment by mamiko-7172** [comment]
マージ済み
