### ISSUE TITLE
[高] 口コミ編集後show.blade.phpに飛べない

### ISSUE THREAD

**Issue by tai-namechan** [ArisaNAKAMURA-GitHub/sweetsguide#84]
店舗情報が受け取れないみたいです

**Comment by tai-namechan** [comment]
ReviewControllerのupdateメソッドのsaveの下に$store = Store::find($id);を書けば解決できると思います

**Comment by chihiro0415** [comment]
あれ、これ最新のコードでもそうなってますか？:eyes:

**Comment by chihiro0415** [comment]
私がみてる最新版だとちゃんとviewにstore情報返してそうです！

**Comment by Tomo9996** [comment]
最新でsaveの後に$store = Store::find($request -> store_id);を入れてありますがいかがでしょうか？

**Comment by tai-namechan** [comment]
masterでマイページから口コミ編集して上書き保存押したらこのエラーが出ました

![スクリーンショット 2021-06-17 9 58 56](https://user-images.githubusercontent.com/76046768/122314235-bff98200-cf52-11eb-9998-1d6a2caa130a.png)

**Comment by Tomo9996** [comment]
やっぱりおかしいですね

**Comment by mamiko-7172** [comment]
マージ済み
