### ISSUE TITLE
［PR中］post_imageの保存処理ができていない

### ISSUE THREAD

**Issue by ArisaNAKAMURA-GitHub** [ArisaNAKAMURA-GitHub/sweetsguide#86]
ReviewController59行目でnull で呼び出せない関数を呼び出すことになってエラーがでている？
![image](https://user-images.githubusercontent.com/73116350/122300791-c67bff80-cf3a-11eb-8352-35228d555801.png)

**Comment by chihiro0415** [comment]
現状
`if($request->file('post_image')->isValid()){`

のところを
`if($request->hasFile('post_image') && $image->isValid())`
に修正してみてほしいです..！ 🙏

**Comment by chihiro0415** [comment]
これもうちょっとだけ修正したら画像でる状態で投稿できるようになるので少しお願いしてもよいですか...！！
変更箇所まとめます 👍 

↓こんな感じ
<img width="900" alt="スクリーンショット 2021-06-17 14 09 06" src="https://user-images.githubusercontent.com/30280895/122335112-bdf4ea80-cf75-11eb-9b97-cdb18d1d51bd.png">

**Comment by chihiro0415** [comment]
まずReviewController@show
（コード内にコメントアウトで説明いれてますがこれは削除してもらって良いです）

①画像があるかどうかのif文を修正
②下書きかどうかのフラグを渡すのをやめた&viewから返す投稿日時（日だけだけど）をcreated_atじゃなくてpublished_atにするので、そのフラグ受け取りのif文をなくす
③redirect させるshowページにidが渡っていないので第二引数でお店のidを渡す

```
    public function store(Request $request)
    {
        $review = new Review;

        $review -> store_id = $request -> store_id;
        $review -> comment = $request -> comment;
        $review -> created_at = $request -> created_at;
        $review -> user_id = Auth::id();
        $review -> review = $request -> review;
        $review -> charge = $request -> charge;
        $review -> ate_thing = $request -> ate_thing;
        $review -> category_id = $request -> category_id;
        $review -> post_image = $request -> post_image;
        
        // これが②
        // if($request->is_published){
        //     $review -> published_at = now();
        // }
        $review -> published_at = $request -> published_at;

        $image = $request->file('post_image');
        // file()で受け取る
        // これが①
        if($request->hasFile('post_image') && $image->isValid()){
            $image_name = $image->getClientOriginalName();
            $review -> post_image = $image->storeAs('public/images', $image_name);
        }

        $review -> save();

       // これが③
        return redirect()->route('stores.show', $request -> store_id);
    }
```

**Comment by chihiro0415** [comment]
reviews/create.blade.php（194行目あたり）

①投稿日時をcreated_atではなくpublished_atにかえる（一緒にタイトルも変更、そもそも投稿日時、を決めて投稿するというより公開日を決めれる、という方が自然なのでこっちにしましょう！）

**現状**
```
<div class="form-group">
      <label class="space">投稿日時</label>
       <input type="date" name="created_at">
</div>
```

**理想**
```
<div class="form-group">
     <label class="space">公開日</label>
     <input type="date" name="published_at">
</div>
```

**Comment by chihiro0415** [comment]
stores/show.blade.php（205行目あたり）

投稿された画像を表示させるためのpathを変更します！

**現状**
```
<img src="{{$review->post_image}}" alt="投稿写真">
```

**理想**
```
<img src="{{ Storage::url($review->post_image) }}" alt="投稿写真">
```

**Comment by chihiro0415** [comment]
以上3つのファイルです！ 🙆‍♀️

**Comment by chihiro0415** [comment]
（そしてみんなのlocal環境で下記コマンドを実行する...！これは授業頭でアナウンスします）
`php artisan storage:link`

**Comment by mamiko-7172** [comment]
修正してマージ済み
